# Generated by Django 3.2.3 on 2021-05-30 23:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(blank=True, max_length=150, verbose_name='Фамилия')),
                ('name', models.CharField(blank=True, max_length=150, verbose_name='Имя')),
                ('patricity', models.CharField(blank=True, max_length=150, verbose_name='Отчество')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('sex', models.CharField(blank=True, choices=[('M', 'Мужской'), ('F', 'Женский')], max_length=1)),
                ('native_language', models.CharField(blank=True, max_length=150, verbose_name='Родной язык')),
                ('citizenship', models.CharField(blank=True, max_length=150, verbose_name='Гражданство')),
                ('martial_status', models.CharField(blank=True, max_length=150, verbose_name='Семейное положение')),
                ('organization', models.CharField(blank=True, max_length=150, verbose_name='Организация')),
                ('job_position', models.CharField(blank=True, max_length=150, verbose_name='Занимаемая должность')),
                ('education', models.CharField(blank=True, max_length=150, verbose_name='Образование')),
                ('home_address', models.CharField(blank=True, max_length=150, verbose_name='Домашний адрес')),
                ('passport', models.CharField(blank=True, max_length=150, verbose_name='Данные паспорта')),
                ('passport_part1_scan_url', models.URLField(blank=True, verbose_name='URLСканаПаспортаРазворот1')),
                ('passport_part2_scan_url', models.URLField(blank=True, verbose_name='URLСканаПаспортаРазворот2')),
                ('email', models.EmailField(blank=True, max_length=150, verbose_name='E-mail')),
                ('personal_phone', models.CharField(blank=True, max_length=150, verbose_name='Мобильный телефон')),
                ('home_phone', models.CharField(blank=True, max_length=150, verbose_name='Домашний телефон')),
                ('work_phone', models.CharField(blank=True, max_length=150, verbose_name='Рабочий телефон')),
                ('work_experience_full_years', models.IntegerField(blank=True, null=True, verbose_name='Стаж полных лет')),
                ('work_experience_current_job', models.IntegerField(blank=True, null=True, verbose_name='Стаж настоящей должности')),
                ('awards', models.TextField(blank=True, verbose_name='Наличие наград')),
                ('training', models.TextField(blank=True, verbose_name='Повышение квалификации')),
                ('organization_membership', models.TextField(blank=True, verbose_name='Членство в организациях')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
