# Generated by Django 3.2.3 on 2021-05-29 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='citizenship',
            field=models.CharField(blank=True, max_length=150, verbose_name='Гражданство'),
        ),
        migrations.AlterField(
            model_name='user',
            name='education',
            field=models.CharField(blank=True, max_length=150, verbose_name='Образование'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=150, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='home_address',
            field=models.CharField(blank=True, max_length=150, verbose_name='Домашний адрес'),
        ),
        migrations.AlterField(
            model_name='user',
            name='home_phone',
            field=models.CharField(blank=True, max_length=150, verbose_name='Домашний телефон'),
        ),
        migrations.AlterField(
            model_name='user',
            name='job_position',
            field=models.CharField(blank=True, max_length=150, verbose_name='Занимаемая должность'),
        ),
        migrations.AlterField(
            model_name='user',
            name='martial_status',
            field=models.CharField(blank=True, max_length=150, verbose_name='Семейное положение'),
        ),
        migrations.AlterField(
            model_name='user',
            name='native_language',
            field=models.CharField(blank=True, max_length=150, verbose_name='Родной язык'),
        ),
        migrations.AlterField(
            model_name='user',
            name='organization',
            field=models.CharField(blank=True, max_length=150, verbose_name='Организация'),
        ),
        migrations.AlterField(
            model_name='user',
            name='passport',
            field=models.CharField(blank=True, max_length=150, verbose_name='Данные паспорта'),
        ),
        migrations.AlterField(
            model_name='user',
            name='passport_part1_scan_url',
            field=models.URLField(blank=True, verbose_name='URLСканаПаспортаРазворот1'),
        ),
        migrations.AlterField(
            model_name='user',
            name='passport_part2_scan_url',
            field=models.URLField(blank=True, verbose_name='URLСканаПаспортаРазворот2'),
        ),
        migrations.AlterField(
            model_name='user',
            name='personal_phone',
            field=models.CharField(blank=True, max_length=150, verbose_name='Мобильный телефон'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', 'Мужской'), ('F', 'Женский')], max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='surname',
            field=models.CharField(blank=True, max_length=150, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='user',
            name='work_experience_current_job',
            field=models.IntegerField(blank=True, verbose_name='Стаж настоящей должности'),
        ),
        migrations.AlterField(
            model_name='user',
            name='work_experience_full_years',
            field=models.IntegerField(blank=True, verbose_name='Стаж полных лет'),
        ),
        migrations.AlterField(
            model_name='user',
            name='work_phone',
            field=models.CharField(blank=True, max_length=150, verbose_name='Рабочий телефон'),
        ),
    ]
