# Generated by Django 3.2.5 on 2021-08-02 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0004_auto_20210718_1404'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('1', 'Шаг 1'), ('2', 'Шаг 2'), ('3', 'Шаг 3'), ('4', 'Шаг 4'), ('5', 'Шаг 5')], max_length=1, verbose_name='Статус заявки')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заявка на аттестацию',
                'verbose_name_plural': 'Заявки на аттестацию',
                'managed': True,
            },
        ),
    ]
