# Generated by Django 3.2.3 on 2021-05-29 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='work_experience_current_job',
            field=models.IntegerField(blank=True, null=True, verbose_name='Стаж настоящей должности'),
        ),
        migrations.AlterField(
            model_name='user',
            name='work_experience_full_years',
            field=models.IntegerField(blank=True, null=True, verbose_name='Стаж полных лет'),
        ),
    ]
