# Generated by Django 3.2.5 on 2021-08-02 14:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='requests',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requests',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='requests',
            name='status',
            field=models.CharField(choices=[('1', 'Шаг 1'), ('2', 'Шаг 2'), ('3', 'Шаг 3'), ('4', 'Шаг 4'), ('5', 'Шаг 5'), ('П', 'Отправлена на проверку'), ('О', 'Отклонена'), ('У', 'Успешно подтверждена'), ('З', 'Завершена работа')], max_length=1, verbose_name='Статус заявки'),
        ),
    ]
