# Generated by Django 3.2.5 on 2021-08-02 14:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210802_1737'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='updatedAt',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='requests',
            name='createdAt',
        ),
        migrations.RemoveField(
            model_name='requests',
            name='updatedAt',
        ),
        migrations.AddField(
            model_name='requests',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Создана'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requests',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлена последний раз'),
        ),
    ]
