# Generated by Django 3.2.5 on 2021-08-02 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210802_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Когда создана'),
        ),
        migrations.AlterField(
            model_name='requests',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Когда обновлена последний раз'),
        ),
    ]
