# Generated by Django 3.2.5 on 2021-08-02 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_rename_requests_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('step_1', 'Шаг 1'), ('step_2', 'Шаг 2'), ('step_3', 'Шаг 3'), ('step_4', 'Шаг 4'), ('step_5', 'Шаг 5'), ('on_check', 'Отправлена на проверку'), ('canceled', 'Отклонена'), ('confirmed', 'Успешно подтверждена'), ('completed', 'Завершена работа')], max_length=9, verbose_name='Статус заявки'),
        ),
    ]
