# Generated by Django 3.2.5 on 2021-08-02 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_request_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photo', verbose_name='Фото'),
        ),
    ]
