# Generated by Django 3.2.6 on 2021-08-08 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_customuser_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='characteristic',
            field=models.ImageField(blank=True, upload_to='photo', verbose_name='Характеристика'),
        ),
    ]
