# Generated by Django 3.2.6 on 2021-08-08 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_customuser_characteristic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='characteristic',
            field=models.ImageField(blank=True, upload_to='characteristic', verbose_name='Характеристика'),
        ),
    ]
