# Generated by Django 3.2.6 on 2021-08-15 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_customuser_characteristic'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='main_diploma_scan',
            field=models.ImageField(blank=True, upload_to='main_diploma', verbose_name='Скан диплома об образовании'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photo', verbose_name='Загрузка фото'),
        ),
    ]
