# Generated by Django 3.2.6 on 2021-08-15 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_customuser_gesture_diploma_scan'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='employment_history',
            field=models.FileField(blank=True, upload_to='employment_history', verbose_name='Заверенная копия трудовой книжки (все страницы)'),
        ),
    ]
