# Generated by Django 3.2.6 on 2021-08-15 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_customuser_employment_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='attestation_certificate_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выдачи сертификата аттестации'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='attestation_certificate_number',
            field=models.CharField(blank=True, max_length=150, verbose_name='Номер сертификата аттестации'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='attestation_certificate_scan',
            field=models.ImageField(blank=True, upload_to='attestation_certificate', verbose_name='Скан сертификата аттестации'),
        ),
    ]
