# Generated by Django 3.2.6 on 2021-08-29 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_alter_request_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='sex',
            field=models.CharField(blank=True, choices=[(None, 'Не указано'), ('M', 'Мужской'), ('F', 'Женский')], max_length=1, verbose_name='Пол'),
        ),
    ]
