# Generated by Django 3.2.6 on 2021-08-29 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_alter_customuser_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cheque',
            field=models.ImageField(blank=True, upload_to='cheque', verbose_name='Чек об оплате организационного взноса'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='sex',
            field=models.CharField(choices=[('N', 'Не указан'), ('M', 'Мужской'), ('F', 'Женский')], default='N', max_length=1, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('step_1', 'Шаг 1'), ('step_2', 'Шаг 2'), ('step_3', 'Шаг 3'), ('step_4', 'Шаг 4'), ('step_5', 'Шаг 5'), ('step_6', 'Шаг 6'), ('on_check', 'Отправлена на проверку'), ('canceled', 'Отклонена'), ('returned', 'Возвращена на доработку'), ('confirmed', 'Успешно подтверждена'), ('completed', 'Завершена работа')], default='step_1', max_length=9, verbose_name='Статус заявки'),
        ),
    ]
