# Generated by Django 3.2.6 on 2021-08-29 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_auto_20210830_0156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='cheque',
        ),
        migrations.AddField(
            model_name='request',
            name='cheque',
            field=models.ImageField(blank=True, upload_to='cheque', verbose_name='Чек об оплате организационного взноса'),
        ),
    ]
