# Generated by Django 3.2.6 on 2021-08-30 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_requestregister'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastRequestOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_order', models.IntegerField(verbose_name='Последний порядковый номер')),
            ],
            options={
                'verbose_name': 'Настроки реестра',
                'verbose_name_plural': 'Настроки реестра',
                'managed': True,
            },
        ),
        migrations.AlterModelOptions(
            name='requestregister',
            options={'managed': True, 'verbose_name': 'Заявка в реестре', 'verbose_name_plural': 'Реестр заявок'},
        ),
    ]
